echo Installing environment with torchjd at ref main...
./setup_env.sh main
echo Done. Computing objective values...
uv run python -m compute main "UPGrad()" agg runtime
echo Done, result saved in results/

echo Installing environment with torchjd at ref qp_solver...
./setup_env.sh qp_solver
echo Done. Computing objective values...
uv run python -m compute qp_solver "UPGrad()" agg runtime
echo Done, result saved in results/